FROM golang:1.12-alpine as gobuilder

ENV GO111MODULE=on

RUN echo http://nl.alpinelinux.org/alpine/v3.6/main > /etc/apk/repositories; \
    echo http://nl.alpinelinux.org/alpine/v3.6/community >> /etc/apk/repositories

RUN apk add --no-cache git bash ca-certificates

# temporary folder for application to read/write files
RUN mkdir -p /tmp /logs

WORKDIR $GOPATH/src/github.com/intel/rsp-sw-toolkit-im-suite-cloud-connector-service

COPY go.mod go.mod
RUN go mod download

COPY . .

RUN ./build.sh

FROM scratch

COPY --from=gobuilder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=gobuilder --chown=2000:2000 /logs /logs
COPY --from=gobuilder --chown=2000:2000 /tmp /tmp
COPY --from=gobuilder --chown=2000:2000 /go/src/github.com/intel/rsp-sw-toolkit-im-suite-cloud-connector-service/cloud-connector-service /

USER 2000
EXPOSE 8080
HEALTHCHECK --interval=5s --timeout=3s CMD ["/cloud-connector-service","-isHealthy"]

ARG GIT_COMMIT=unspecified
LABEL git_commit=$GIT_COMMIT

ENTRYPOINT ["/cloud-connector-service"]

