# Apache v2 license
#  Copyright (C) <2019> Intel Corporation
#
#  SPDX-License-Identifier: Apache-2.0
#

version: '3.4'

services:

  cloud-connector:
    image: rsp/cloud-connector-service:dev
    user: "2000:2000"
    ports:
      - "8080:8080"
    logging:
      options:
        max-size: "100m"
        max-file: "5"
    environment:
      loggingLevel: "info"
      telemetryEndpoint: ""
      telemetryDataStoreName: "telemetry"      
      port: "8080"
      serviceName: "Cloud Connector Service"
      httpsProxyURL: ""
